// XML name character ranges
export const NAME_START_CHAR =
  ':A-Z_a-z\\u00c0-\\u00d6\\u00d8-\\u00f6\\u00f8-\\u02ff\\u0370-\\u037d\\u037f-\\u1fff' +
  '\\u200c-\\u200d\\u2070-\\u218f\\u2c00-\\u2fef\\u3001-\\ud7ff\\uf900-\\ufdcf\\ufdf0-\\ufffd';
export const NAME_CHAR = NAME_START_CHAR + '\\-0-9\\u00B7\\u0300-\\u036F\\u203F\\u2040';

// HTML elements that only contain raw text
export const RAW = new Set(['script', 'style']);

// HTML elements that only contain raw text and entities
export const RCDATA = new Set(['title', 'textarea']);

// HTML elements without end tags
export const EMPTY = new Set([
  'area',
  'base',
  'br',
  'col',
  'embed',
  'hr',
  'img',
  'input',
  'keygen',
  'link',
  'menuitem',
  'meta',
  'param',
  'source',
  'track',
  'wbr'
]);

// HTML elements with optional end tags and elements that break paragraphs
export const END: Record<string, string> = {
  address: 'p',
  article: 'p',
  aside: 'p',
  blockquote: 'p',
  body: 'head',
  optgroup: 'optgroup',
  option: 'option',
  details: 'p',
  dialog: 'p',
  div: 'p',
  dl: 'p',
  fieldset: 'p',
  figcaption: 'p',
  figure: 'p',
  footer: 'p',
  form: 'p',
  h1: 'p',
  h2: 'p',
  h3: 'p',
  h4: 'p',
  h5: 'p',
  h6: 'p',
  header: 'p',
  hgroup: 'p',
  hr: 'p',
  main: 'p',
  menu: 'p',
  nav: 'p',
  ol: 'p',
  p: 'p',
  pre: 'p',
  section: 'p',
  table: 'p',
  ul: 'p'
};

// Container HTML elements that create their own scope
export const SCOPE = new Set(['math', 'svg']);

// HTML table elements with optional end tags
const TABLE = new Set(['colgroup', 'tbody', 'td', 'tfoot', 'th', 'thead', 'tr']);

// HTML elements with optional end tags and scoping rules
export const CLOSE: Record<string, Record<string, Set<string>>> = {
  li: {allowed: new Set(['li']), scope: new Set(['ul', 'ol'])},
  tr: {allowed: new Set(['tr']), scope: new Set(['table'])},
  colgroup: {allowed: TABLE, scope: new Set(['table'])},
  tbody: {allowed: TABLE, scope: new Set(['table'])},
  tfoot: {allowed: TABLE, scope: new Set(['table'])},
  thead: {allowed: TABLE, scope: new Set(['table'])},
  dd: {allowed: new Set(['dd', 'dt']), scope: new Set(['dl'])},
  dt: {allowed: new Set(['dd', 'dt']), scope: new Set(['dl'])},
  rp: {allowed: new Set(['rp', 'rt']), scope: new Set(['dl'])},
  rt: {allowed: new Set(['rp', 'rt']), scope: new Set(['dl'])},
  td: {allowed: new Set(['th', 'td']), scope: new Set(['table'])},
  th: {allowed: new Set(['th', 'td']), scope: new Set(['table'])}
};

// HTML parent elements that signal no more content when closed, but that are also phrasing content
export const NO_MORE_CONTENT: Record<string, Set<string>> = {
  ruby: new Set(['rt', 'rp']),
  select: new Set(['option', 'optgroup'])
};

// HTML elements categorized as phrasing content (and obsolete inline elements)
const OBSOLETE = ['acronym', 'applet', 'basefont', 'big', 'font', 'strike', 'tt'];
export const PHRASING = new Set([
  ...OBSOLETE,
  'a',
  'abbr',
  'area',
  'audio',
  'b',
  'bdi',
  'bdo',
  'br',
  'button',
  'canvas',
  'cite',
  'code',
  'data',
  'datalist',
  'del',
  'dfn',
  'em',
  'embed',
  'i',
  'iframe',
  'img',
  'input',
  'ins',
  'kbd',
  'keygen',
  'label',
  'link',
  'map',
  'mark',
  'math',
  'meta',
  'meter',
  'noscript',
  'object',
  'output',
  'picture',
  'progress',
  'q',
  'ruby',
  's',
  'samp',
  'script',
  'select',
  'slot',
  'small',
  'span',
  'strong',
  'sub',
  'sup',
  'svg',
  'template',
  'textarea',
  'time',
  'u',
  'var',
  'video',
  'wbr'
]);

// HTML elements that don't get their self-closing flag acknowledged
export const BLOCK = new Set([
  'a',
  'address',
  'applet',
  'article',
  'aside',
  'b',
  'big',
  'blockquote',
  'body',
  'button',
  'caption',
  'center',
  'code',
  'col',
  'colgroup',
  'dd',
  'details',
  'dialog',
  'dir',
  'div',
  'dl',
  'dt',
  'em',
  'fieldset',
  'figcaption',
  'figure',
  'font',
  'footer',
  'form',
  'frameset',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'head',
  'header',
  'hgroup',
  'html',
  'i',
  'iframe',
  'li',
  'listing',
  'main',
  'marquee',
  'menu',
  'nav',
  'nobr',
  'noembed',
  'noframes',
  'noscript',
  'object',
  'ol',
  'optgroup',
  'option',
  'p',
  'plaintext',
  'pre',
  'rp',
  'rt',
  's',
  'script',
  'section',
  'select',
  'small',
  'strike',
  'strong',
  'style',
  'summary',
  'table',
  'tbody',
  'td',
  'template',
  'textarea',
  'tfoot',
  'th',
  'thead',
  'title',
  'tr',
  'tt',
  'u',
  'ul',
  'xmp'
]);
