name: coverage
on: [push, pull_request]
jobs:
  coveralls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: npm install
        run: npm i
      - name: npm run build
        run: npm run build
      - name: npm run coverage:ci
        run: npm run coverage:ci
      - name: coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
